site_name: BKEngine 文档中心
theme_dir: 'theme'
theme: readthedocs
site_description: "BKEngine - 专业的AVG/Galgame游戏引擎 - 官方教程及文档中心~"
site_author: 面包工坊
site_url: "http://docs.bakery.moe"
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />本文档采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。
extra_css: [themefix.css]
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - sane_lists
    - smarty
    - extra
    - tables
pages:
    - 首页: index.md
    - 常见问题（必看！）: faq.md
    - 旧教程:
        - 快速入门: old/quickstart.md
        - 图像: old/image.md
        - 声音: old/sound.md
        - 语法进阶: old/grammar.md
        - 动画: old/animation.md
    - 新教程（施工中）:
        - 快速入门: new/quickstart.md
    - 脚本命令手册:
        - 精灵类: bkscr/sprite.md
        - 音频类: bkscr/sound.md
    - Parser 系统: 
        - 基本语法: parser/index.md
        - 全局函数: parser/engine/functions.md
        - 全局类: 
            - 按钮类: parser/engine/class/button.md
            - CSV文档类: parser/engine/class/csvparser.md
            